name: build-windows

on:
  push:
    branches: main

jobs:
  main:
    runs-on: windows-2019
    steps:
      -
        name: Read version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Checkout, build, and push
        uses: actions/checkout@v2
        working-directory: .
        run: |
          docker login -u $env:USERNAME -p $env:PASSWORD
          docker build alpine-s6
          docker image push bcgdesign/alpine-s6:latest bcgdesign/alpine-s6:${{ steps.version.outputs.content }}
          docker logout
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
