name: build-windows

on:
  push:
    branches: main

jobs:
  main:
    runs-on: windows-2019
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Build and push to Docker Hub
        working-directory: .
        run: |
          docker login -u $env:USERNAME -p $env:PASSWORD
          Get-Content Dockerfile-windows | docker build -
          docker image push bcgdesign/alpine-s6:latest
          docker image push bcgdesign/alpine-s6:${{ steps.version.outputs.content }}
          docker logout
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
